// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt9-hQALciav9T_zKylldlnHW0eYrBkI0',
    appId: '1:993267263032:web:b1071693f8f039f97068cd',
    messagingSenderId: '993267263032',
    projectId: 'application-99be3',
    authDomain: 'application-99be3.firebaseapp.com',
    storageBucket: 'application-99be3.firebasestorage.app',
    measurementId: 'G-0ZEH8EWZ96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDETtF6TmACN4KsSVohJoVqSxDB0su5wp8',
    appId: '1:993267263032:android:4835ee2d6efcef857068cd',
    messagingSenderId: '993267263032',
    projectId: 'application-99be3',
    storageBucket: 'application-99be3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdX1eEFHVndNtQyXvwGxDmDEvPh3B0Els',
    appId: '1:993267263032:ios:94324b563a098fd87068cd',
    messagingSenderId: '993267263032',
    projectId: 'application-99be3',
    storageBucket: 'application-99be3.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdX1eEFHVndNtQyXvwGxDmDEvPh3B0Els',
    appId: '1:993267263032:ios:94324b563a098fd87068cd',
    messagingSenderId: '993267263032',
    projectId: 'application-99be3',
    storageBucket: 'application-99be3.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt9-hQALciav9T_zKylldlnHW0eYrBkI0',
    appId: '1:993267263032:web:ef252b2006bb652c7068cd',
    messagingSenderId: '993267263032',
    projectId: 'application-99be3',
    authDomain: 'application-99be3.firebaseapp.com',
    storageBucket: 'application-99be3.firebasestorage.app',
    measurementId: 'G-QN1DRP4G5Z',
  );
}
